board/urls.py
from django.urls import path

from . import views

app_name = "board"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("show_board/", views.ShowBoardView.as_view(), name="show_board"),
    path("add_task/", views.AddTaskView.as_view(), name="add_task"),
    path("create_board/", views.CreateBoardView.as_view(), name="create_board"),
    path(
        "user_profile/<int:pk>/", views.UserProfileView.as_view(), name="user_profile"
    ),
    # path('edit_task/<int:task_id>/', views.EditTaskView.as_view(), name='edit_task'),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("about/", views.AboutView.as_view(), name="about"),
    path(
        "add_task_success/", views.AddTaskSuccessView.as_view(), name="add_task_success"
    ),
    path("add_task_fail/", views.AddTaskFailView.as_view(), name="add_task_fail"),
    path("user_list/", views.UserListView.as_view(), name="user_list"),
    # path('assign_task/<int:task_id>/', views.AssignTaskView.as_view(), name='assign_task'),
    path(
        "mark_completed/<int:task_id>/",
        views.MarkCompletedView.as_view(),
        name="mark_completed",
    ),
    path(
        "resign_task/<int:task_id>", views.ResignTaskView.as_view(), name="resign_task"
    ),
    path("join_board", views.JoinBoardView.as_view(), name="join_board"),
]

htmx_views = [
    path("tasks/<int:pk>/delete", views.delete_task, name="delete_task"),
    path("tasks/<int:pk>/edit", views.edit_task, name="edit_task"),
    path("tasks/<int:pk>/assign", views.assign_task, name="assign_task"),
    path("tasks/<int:pk>/resign", views.resign_task, name="resign_task"),
    path("tasks/<int:pk>/complete", views.complete_task, name="complete_task"),
]

urlpatterns += htmx_views

home_manager/urls.py
"""home_manager URL Configuration
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# from django_registration.backends.one_step.views import RegistrationView

urlpatterns = [
    path("", include("board.urls")),
    path("admin/", admin.site.urls),
    # path('accounts/', include('django_registration.backends.one_step.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("messagebox/", include("messagebox.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/partials/tasks.html
{% load static %}
<div class="row"
     id="tasks"
     hx-target="#tasks"
     hx-swap="outerHTML">
    <div class="col-12 col-md-4 status-column">
        <h3 class="text-center">To Do:</h3>
        <ul class="list-unstyled">
            {% for task in tasks.todo %}
            <li>
                <!-- color coding task priority -->
                {% if task.priority == 'a' %}
                <div class="card to-do high-priority">
                    {% elif task.priority == 'b' %}
                    <div class="card to-do medium-priority">
                        {% else %}
                        <div class="card to-do low-priority">
                            {% endif %}
                    <div class="card-header">
                        {{ task.title }}
                    </div>
                    <div class="card-body">
                        <p class="card-text">{{ task.description }}</p>
                        <a hx-patch="{% url 'board:assign_task' task.id %}" class="btn btn-primary btn-sm">I'll do it</a>
                        <a hx-get="{% url 'board:edit_task' task.id %}" hx-target="#dialog" class="btn btn-primary btn-sm">Edit</a>
                        <a hx-delete="{% url 'board:delete_task' task.id %}"
                           hx-confirm="Are you sure you want to delete this task?"
                           class="btn btn-primary btn-sm">Delete</a>
                    </div>
                </div>
            </li>
            {% endfor %}
        </ul>
    </div>
    <div class="col-12 col-md-4 status-column">
        <h3 class="text-center">In Progress {{ current_wip }}/{{ board.max_wip }}</h3>
        <ul class="list-unstyled">
            {% for task in tasks.wip %}
            <div class="card wip">
                <div class="card-header d-flex justify-content-between">
                    <span>{{ task.title }}</span><span>{{task.assigned_to }} <img src="{% get_media_prefix %}/{{ user.userprofile.picture }}" class="profile-picture-small"></span>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ task.description }}</p>
                    <a href="{% url 'board:mark_completed' task.id %}" class="btn btn-primary btn-sm">Completed</a>
                    <a href="{% url 'board:resign_task' task.id %}" class="btn btn-primary btn-sm">Resign</a>
                    <a hx-delete="{% url 'board:delete_task' task.id %}"
                       hx-confirm="Are you sure you want to delete this task?"
                       class="btn btn-primary btn-sm">Delete</a>
                </div>
            </div>
            {% endfor %}
        </ul>
    </div>
    <div class="col-12 col-md-4 status-column">
        <h3 class="text-center">Completed:</h3>
        <ul class="list-unstyled">
            {% for task in tasks.done %}
            <div class="card done">
                <div class="card-header d-flex justify-content-between">
                    <span>{{ task.title }}</span><span>{{task.assigned_to }} <img src="{% get_media_prefix %}/{{ user.userprofile.picture }}" class="profile-picture-small"></span>
                </div>
                <div class="card-body">
                    <p class="card-text">{{ task.description }}</p>
                    <a hx-delete="{% url 'board:delete_task' task.id %}"
                       hx-confirm="Are you sure you want to delete this task?"
                       class="btn btn-primary btn-sm">Delete</a>
                </div>
            </div>
            {% endfor %}
        </ul>

    </div>
</div>