board/urls.py
from django.urls import path

from . import views

app_name = "board"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("show_board/", views.ShowBoardView.as_view(), name="show_board"),
    path("add_task/", views.AddTaskView.as_view(), name="add_task"),
    path("create_board/", views.CreateBoardView.as_view(), name="create_board"),
    path(
        "user_profile/<int:pk>/", views.UserProfileView.as_view(), name="user_profile"
    ),
    # path('edit_task/<int:task_id>/', views.EditTaskView.as_view(), name='edit_task'),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("about/", views.AboutView.as_view(), name="about"),
    path(
        "add_task_success/", views.AddTaskSuccessView.as_view(), name="add_task_success"
    ),
    path("add_task_fail/", views.AddTaskFailView.as_view(), name="add_task_fail"),
    path("user_list/", views.UserListView.as_view(), name="user_list"),
    # path('assign_task/<int:task_id>/', views.AssignTaskView.as_view(), name='assign_task'),
    path(
        "mark_completed/<int:task_id>/",
        views.MarkCompletedView.as_view(),
        name="mark_completed",
    ),
    path(
        "resign_task/<int:task_id>", views.ResignTaskView.as_view(), name="resign_task"
    ),
    path("join_board", views.JoinBoardView.as_view(), name="join_board"),
]

htmx_views = [
    path("tasks/<int:pk>/delete", views.delete_task, name="delete_task"),
    path("tasks/<int:pk>/edit", views.edit_task, name="edit_task"),
    path("tasks/<int:pk>/assign", views.assign_task, name="assign_task"),
    path("tasks/<int:pk>/resign", views.resign_task, name="resign_task"),
    path("tasks/<int:pk>/complete", views.complete_task, name="complete_task"),
]

urlpatterns += htmx_views

home_manager/urls.py
"""home_manager URL Configuration
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# from django_registration.backends.one_step.views import RegistrationView

urlpatterns = [
    path("", include("board.urls")),
    path("admin/", admin.site.urls),
    # path('accounts/', include('django_registration.backends.one_step.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("messagebox/", include("messagebox.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messagebox/urls.py
from django.urls import path

from . import views

app_name = "messagebox"
urlpatterns = [
    path("", views.MessagesView.as_view(), name="messages"),
    path("inbox/", views.InboxView.as_view(), name="inbox"),
    path("sent/", views.SentView.as_view(), name="sent"),
    path(
        "delete_message/<int:message_id>/",
        views.DeleteMessageView.as_view(),
        name="delete_message",
    ),
    path("new_message/", views.NewMessageView.as_view(), name="new_message"),
    path(
        "show_message/<int:message_id>",
        views.ShowMessageView.as_view(),
        name="show_message",
    ),
]

board/models.py
from django.contrib.auth.models import User
from django.db import models


class Board(models.Model):
    name = models.CharField(max_length=128, unique=True)
    max_wip = models.IntegerField(default=5)
    current_wip = models.IntegerField(default=0)
    created_by = models.ForeignKey(User, on_delete=models.CASCADE)
    # TODO remove the access code/ will use invitations to boards
    access_code = models.CharField(max_length=128)

    def __str__(self):
        return self.name


class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    picture = models.ImageField(
        default="default.jpg", upload_to="profile_images", blank=True, null=True
    )
    likes = models.IntegerField(default=0)
    board = models.ForeignKey(Board, on_delete=models.SET_NULL, default=None, null=True)

    def __str__(self):
        return self.user.username


class Task(models.Model):
    HIGH = "a"
    MEDIUM = "b"
    LOW = "c"
    priority_choices = [(HIGH, "High"), (MEDIUM, "Medium"), (LOW, "Low")]

    status_choices = [("todo", "To Do"), ("wip", "In Progress"), ("done", "Done")]

    board = models.ForeignKey(Board, on_delete=models.CASCADE)
    assigned_to = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    priority = models.CharField(
        choices=priority_choices, default=MEDIUM, blank=True, max_length=1
    )
    title = models.CharField(max_length=256)
    description = models.TextField(max_length=1024, default="", blank=True)
    status = models.CharField(choices=status_choices, default="todo", max_length=4)
    date_created = models.DateTimeField(auto_now_add=True)
    date_completed = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.title

board/forms.py
from django.contrib.auth.models import User
from board.models import Board, Task
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm


class RegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email"]


class TaskForm(ModelForm):
    class Meta:
        model = Task
        fields = ["title", "description", "priority"]


class BoardForm(ModelForm):
    class Meta:
        model = Board
        fields = ["name", "max_wip", "access_code"]

board/views.py
from collections import namedtuple

from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.http import HttpResponse
from django.shortcuts import render, redirect
from django.urls import reverse
from django.utils import timezone
from django.views import View
from django.views.decorators.http import require_http_methods

from messagebox.models import Message

from .forms import RegisterForm, TaskForm, BoardForm
from .models import Board, Task, UserProfile


class IndexView(View):
    def get(self, request):
        # TODO
        """If user is not logged in, display basic info about the page and sample pictures.
        If user is logged in, display welcome message and overview of user's activity and tasks."""
        context_dict = {}
        if request.user.is_authenticated:
            user_profile = UserProfile.objects.get(user=request.user)
            context_dict["board_id"] = user_profile.board
        return render(request, "board/index.html", context=context_dict)


class AboutView(View):
    def get(self, request):
        """Display description of the page."""
        return render(request, "board/about.html")


class ShowBoardView(LoginRequiredMixin, View):
    def get(self, request):
        """Display user's board. If no board, display links to create or join one."""
        board = request.user.userprofile.board
        context_dict = {}
        if board:
            context_dict["board"] = board
            context_dict["tasks"] = get_tasks_by_status(board)
            context_dict["current_wip"] = len(context_dict["tasks"].wip)
        else:
            context_dict["board"] = None
        return render(request, "board/show_board.html", context=context_dict)


class AddTaskView(LoginRequiredMixin, View):
    """Add task to user board"""

    def get(self, request):
        board = request.user.userprofile.board
        if not board:
            return redirect(reverse("board:show_board"))
        form = TaskForm()
        return render(request, "board/create_task.html", context={"form": form})

    def post(self, request):
        form = TaskForm(request.POST)
        if form.is_valid():
            new_task = form.save(commit=False)
            new_task.date_created = timezone.now()
            new_task.status = "todo"
            new_task.board = request.user.userprofile.board
            if not new_task.board:
                return redirect(reverse("board:add_task_fail"))
            new_task.save()
            return redirect(reverse("board:add_task_success"))
        else:
            return redirect(
                "board:add_task_fail",
                context={"message": "Something went wrong when adding the task"},
            )


class AddTaskSuccessView(View):
    def get(self, request):
        return render(request, "board/add_task_success.html")


class AddTaskFailView(View):
    def get(self, request):
        return render(request, "board/add_task_fail.html")


class CreateBoardView(LoginRequiredMixin, View):
    """Create a board for currently logged in user"""

    def get(self, request):
        form = BoardForm()
        return render(request, "board/create_board.html", context={"form": form})

    def post(self, request):
        form = BoardForm(request.POST)
        if form.is_valid():
            new_board = form.save(commit=False)
            new_board.created_by = request.user
            new_board.save()
            profile = request.user.userprofile
            profile.board_id = new_board.id
            profile.save()
            return redirect(reverse("board:index"))
        else:
            redirect(
                "board:add_task_fail",
                {"message": "Something went wrong when adding the board"},
            )


class UserProfileView(LoginRequiredMixin, View):
    def get(self, request, pk):
        """Display user profile."""
        context_dict = {"profile": get_user_profile(pk)}
        return render(request, "board/user_profile.html", context=context_dict)

    def post(self, request, pk):
        # TODO
        """Update profile picture. Show only on currently logged in user's profile."""
        profile = get_user_profile(pk)
        profile.picture = request.FILES.get("profile_picture")
        # Rename the profile picture to user's name
        # profile.picture.name = profile.picture.name.split(".")
        profile.save()
        context_dict = {"profile": profile}
        return render(request, "board/user_profile.html", context_dict)


class MarkCompletedView(LoginRequiredMixin, View):
    def get(self, request, task_id):
        board = request.user.userprofile.board
        board.current_wip -= 1
        task = Task.objects.get(pk=task_id)
        task.status = "done"
        task.save()
        board.save()
        return redirect(reverse("board:show_board"))


class ResignTaskView(LoginRequiredMixin, View):
    def get(self, request, task_id):
        board = request.user.userprofile.board
        board.current_wip -= 1
        task = Task.objects.get(pk=task_id)
        task.status = "todo"
        task.assigned_to = None
        task.save()
        board.save()
        return redirect(reverse("board:show_board"))


class RegisterView(View):
    def get(self, request):
        form = RegisterForm()
        return render(request, "board/register.html", {"form": form})

    def post(self, request):
        form = RegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            user_profile = UserProfile.objects.create(user=user, likes=0, board_id=None)
            user_profile.save()
            # Automatically login the newly registered user
            user_to_log = authenticate(
                request,
                username=form.cleaned_data["username"],
                password=form.cleaned_data["password1"],
            )
            login(request, user_to_log)
            return redirect(reverse("board:index"))
        else:
            messages.warning(request, "Please correct the error below.")
            return render(request, "board/register.html", {"form": form})


class UserListView(LoginRequiredMixin, View):
    def get(self, request):
        users = User.objects.exclude(username=request.user.username)
        return render(request, "board/user_list.html", context={"users": users})


class AssignTaskView(LoginRequiredMixin, View):
    def get(self, request, task_id):
        board = request.user.userprofile.board
        if board.current_wip < board.max_wip:
            task = Task.objects.get(pk=task_id)
            task.assigned_to = request.user
            task.status = "wip"
            task.save()
            board.current_wip += 1
            board.save()
            return redirect(reverse("board:show_board"))


class JoinBoardView(LoginRequiredMixin, View):
    def get(self, request):
        boards = Board.objects.all()
        boards_with_creators = []
        for board in boards:
            creator = board.created_by
            boards_with_creators.append((board, creator))
        return render(
            request, "board/join_board.html", context={"boards": boards_with_creators}
        )

    def post(self, request, board):
        board_creator = board.created_by
        send_message(request.user.id, board_creator.id, "placeholder")


# Helper functions


def prepare_tasks_data(user):
    """Prepare context dictionary for rendering tasks on the board."""
    profile = get_user_profile(user.pk)
    data = {}
    data["board"] = profile.board
    data["tasks"] = get_tasks_by_status(data["board"])
    data["current_wip"] = len(data["tasks"].wip)
    return data


def get_user_profile(pk):
    user = User.objects.get(pk=pk)
    profile = user.userprofile
    return profile


def get_tasks_by_status(board: Board) -> namedtuple:
    todo = Task.objects.filter(board=board.id, status="todo").order_by(
        "priority", "-date_created"
    )
    wip = Task.objects.filter(board=board.id, status="wip")
    done = Task.objects.filter(board=board.id, status="done").order_by(
        "-date_completed"
    )
    TaskData = namedtuple("TaskData", "todo wip done")
    data = TaskData(todo=todo, wip=wip, done=done)
    return data


# TODO (for sending automated messages)
def send_message(
    from_user,
    to_user,
    title="untitled",
    message="",
):
    message = Message.objects.create(
        from_user=from_user, to_user=to_user, title=title, message=message
    )


# Function views for HTMX


@require_http_methods(["DELETE"])
def delete_task(request, pk):
    Task.objects.filter(pk=pk).delete()
    context_dict = prepare_tasks_data(request.user)
    return render(request, "partials/tasks.html", context=context_dict)


@require_http_methods(["GET", "POST"])
def edit_task(request, pk):
    if request.method == "GET":
        task = Task.objects.get(pk=pk)
        form = TaskForm(instance=task)
        context_dict = {"form": form, "instance": task}
        return render(request, "board/edit_task.html", context_dict)
    else:
        task = Task.objects.get(pk=pk)
        form = TaskForm(request.POST, instance=task)
        if form.is_valid():
            form.save()
            return HttpResponse(status=204)


def assign_task(request, pk):
    task = Task.objects.filter(pk=pk).first()
    task.assigned_to = request.user
    task.status = "wip"
    task.save()
    context_dict = prepare_tasks_data(request.user)
    return render(request, "partials/tasks.html", context=context_dict)


def resign_task():
    return None


def complete_task(request, pk):
    task = Task.objects.filter(pk=pk).first()
    task.status = "done"
    task.save()
    context_dict = prepare_tasks_data(request.user)
    return render(request, "partials/tasks.html", context=context_dict)

templates/board/add_task_fail.html
{% extends 'board/base.html' %}
{% load static %}

{% block title_block %}
Fail
{% endblock %}

{% block content_block %}
{% if user.userprofile.board%}
<p>Something went wrong when adding the task</p>
{% else %}
<p>You need to <a href="{% url 'board:create_board' %}">create</a> or <a href="#">join</a> a board to be able to add
    tasks.</p>
{% endblock %}

templates/board/base.html
<!doctype html>
{% load static %}

<html lang="en">

<head>
  <title>{% block title_block %}{% endblock %}</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <!-- Favicon -->
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}" />

  <!-- Font Awesome Icons -->
  <script src="https://kit.fontawesome.com/bf7a298da8.js" crossorigin="anonymous"></script>

  <!-- Bootstrap CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">

  <!-- Fonts -->

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>

  <!-- Custom styles -->
  <link href="{% static 'css/styles.css' %}" rel="stylesheet">
</head>

<body>

  <!-- Bootstrap sidebar -->
  <div class="container-fluid">
    <div class="row flex-nowrap">
      <div class="col-auto col-md-3 col-xl-2 px-sm-2 px-0 bg-dark">
        <div class="d-flex flex-column align-items-center align-items-sm-start px-3 pt-2 text-white min-vh-100">
          <a href="/" class="d-flex align-items-center pb-3 mb-md-0 me-md-auto text-white text-decoration-none">
            <span class="fs-5 d-none d-sm-inline">Home Manager</span>
          </a>

          <ul class="nav nav-pills flex-column mb-sm-auto mb-0 align-items-center align-items-sm-start" id="menu">
            <li class="nav-item">
              <a href="{% url 'board:about' %}" class="nav-link align-middle px-0">
                <i class="fa-regular fa-circle-question"></i> <span class="ms-1 d-none d-sm-inline">About</span>
              </a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item">
              <a href="{% url 'board:show_board' %}" class="nav-link align-middle px-0">
                <i class="fa-regular fa-calendar"></i> <span class="ms-1 d-none d-sm-inline">Board</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'board:add_task' %}" class="nav-link align-middle px-0">
                <i class="fa-solid fa-circle-plus"></i> <span class="ms-1 d-none d-sm-inline">Add a Task</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'messagebox:messages' %}" class="nav-link align-middle px-0">
                <i class="fa-solid fa-message"></i> <span class="ms-1 d-none d-sm-inline">Messages</span>
              </a>
            </li>

            {% else %}
            <li class="nav-item">
              <a href="{% url 'board:register' %}" class="nav-link align-middle px-0">
                <i class="fa-solid fa-user-plus"></i> <span class="ms-1 d-none d-sm-inline">Register</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="{% url 'login' %}" class="nav-link align-middle px-0">
                <i class="fa-solid fa-user-check"></i> <span class="ms-1 d-none d-sm-inline">Log In</span>
              </a>
            </li>
            <li class="nav-item">
              <a href="#" class="nav-link align-middle px-0">
                <i class="fa-regular fa-calendar"></i> <span class="ms-1 d-none d-sm-inline">Board Demo</span>
              </a>
            </li>

            {% endif %}
          </ul>
          <hr>
          <div class="dropdown pb-4">
            {% if user.is_authenticated %}
            <a href="#" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
              id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
              {% if user.userprofile.picture %}
              <img src="{% get_media_prefix %}/{{ user.userprofile.picture }}" class="profile-picture-small">
              {% else %}
              <img src="{% static 'images/default-profile-picture.png' %}" alt="profile picture" class="profile-picture-small">
              {% endif %}
              <span class="d-none d-sm-inline mx-1">{{ user.username }}</span>
            </a>

            <ul class="dropdown-menu dropdown-menu-dark text-small shadow">
              <li><a class="dropdown-item" href="{% url 'board:user_list' %}">User list</a></li>
              <li><a class="dropdown-item" href="{% url 'board:user_profile' user.pk %}">Profile</a></li>
              <li>
                <hr class="dropdown-divider">
              </li>
              <li><a class="dropdown-item" href="{% url 'logout' %}">Sign out</a></li>
            </ul>
            {% endif %}
          </div>
          <div class=" contact d-flex flex-column flex-lg-row justify-content-around align-items-center">
            <a href="https://github.com/Kalarebka"><i class="fa-brands fa-github p-3"></i></a>
            <a href=""><i class="fa-brands fa-linkedin p-3"></i></a>
            <a href="mailto:ewelina.sitarczyk@gmail.com"><i class="fa-solid fa-at p-3"></i></a>
          </div>
          <div class="nav-footer d-none d-md-block">
            <p>© 2022 Ewelina Sitarczyk</p>
          </div>
        </div>
      </div>
      <div class="col py-3">
        {% block content_block %}{% endblock %}
      </div>
    </div>
  </div>

  <div id="modal" class="modal fade">
    <div id="dialog" class="modal-dialog" hx-target="this"></div>
  </div>


  <!-- Bootstrap JavaScript -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous">
  </script>
  <!-- HTMX -->
  <script src="https://unpkg.com/htmx.org@1.1.0"></script>
  <script>
      document.body.addEventListener('htmx:configRequest', (event) => {
        event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
      })
    </script>
  <script>
    ;(function () {
  const modal = new bootstrap.Modal(document.getElementById("modal"))

  htmx.on("htmx:afterSwap", (e) => {
    // Response targeting #dialog => show the modal
    if (e.detail.target.id == "dialog") {
      modal.show()
    }
  })

  htmx.on("htmx:beforeSwap", (e) => {
    // Empty response targeting #dialog => hide the modal
    if (e.detail.target.id == "dialog" && !e.detail.xhr.response) {
      modal.hide()
      e.detail.shouldSwap = false
    }
  })

  // Remove dialog content after hiding
  htmx.on("hidden.bs.modal", () => {
    document.getElementById("dialog").innerHTML = ""
  })
})()
</script>
</body>

</html>

templates/board/base_old.html
<!doctype html>
{% load static %}

<html lang="en">
  <head>
    <title>{% block title_block %}{% endblock %}</title>  
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Font Awesome Icons -->
    <script src="https://kit.fontawesome.com/e9965beb6f.js" crossorigin="anonymous"></script>

    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }
    
        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }
      </style>
    
    
    
    <!-- Custom styles for this template -->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet">
  </head>
  <body hx-headers='{"X-CSRFToken": "{{ csrf_token }}"}'>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'board:index' %}">Home Manager</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item"><a class="nav-link" href="{% url 'board:about' %}">About</a></li>
          {% if user.is_authenticated %}
          <li class="nav-item"><a class="nav-link" href="{% url 'board:show_board' %}">Board</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'board:user_profile' %}">Profile</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'logout' %}">Log Out</a></li>
          {% else %}
          <li class="nav-item"><a class="nav-link" href="{% url 'board:register' %}">Register</a></li>
          <li class="nav-item"><a class="nav-link" href="{% url 'login' %}">Log In</a></li>
          <li class="nav-item"><a class="nav-link" href="#">Board Demo</a></li>
          {% endif %}
        </ul>
      </div>
    </div>
  </nav>
  
  <main class="container">
{% block content_block %}{% endblock %}
  </main>
  
  


    <footer class="bg-dark text-center text-white">
      <div class="text-center p-3" style="background-color: rgba(0, 0, 0, 0.2);">
        © 2022 Copyright: Ewelina Sitarczyk
      </div>
    </footer>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
  <script src="https://unpkg.com/htmx.org@1.1.0"></script>
    </body>
</html>



<!-- new base nav items before I inevitably break them -->


<li class="nav-item">
  <a href="#" class="nav-link align-middle px-0">
      <i class="fs-4 bi-house"></i> <span class="ms-1 d-none d-sm-inline">Home</span>
  </a>
</li>
<li>
  <a href="#submenu1" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
      <i class="fs-4 bi-speedometer2"></i> <span class="ms-1 d-none d-sm-inline">Dashboard</span> </a>
  <ul class="collapse show nav flex-column ms-1" id="submenu1" data-bs-parent="#menu">
      <li class="w-100">
          <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1 </a>
      </li>
      <li>
          <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2 </a>
      </li>
  </ul>
</li>
<li>
  <a href="#" class="nav-link px-0 align-middle">
      <i class="fs-4 bi-table"></i> <span class="ms-1 d-none d-sm-inline">Orders</span></a>
</li>
<li>
  <a href="#submenu2" data-bs-toggle="collapse" class="nav-link px-0 align-middle ">
      <i class="fs-4 bi-bootstrap"></i> <span class="ms-1 d-none d-sm-inline">Bootstrap</span></a>
  <ul class="collapse nav flex-column ms-1" id="submenu2" data-bs-parent="#menu">
      <li class="w-100">
          <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 1</a>
      </li>
      <li>
          <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Item</span> 2</a>
      </li>
  </ul>
</li>
<li>
  <a href="#submenu3" data-bs-toggle="collapse" class="nav-link px-0 align-middle">
      <i class="fs-4 bi-grid"></i> <span class="ms-1 d-none d-sm-inline">Products</span> </a>
      <ul class="collapse nav flex-column ms-1" id="submenu3" data-bs-parent="#menu">
      <li class="w-100">
          <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 1</a>
      </li>
      <li>
          <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 2</a>
      </li>
      <li>
          <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 3</a>
      </li>
      <li>
          <a href="#" class="nav-link px-0"> <span class="d-none d-sm-inline">Product</span> 4</a>
      </li>
  </ul>
</li>
<li>
  <a href="#" class="nav-link px-0 align-middle">
      <i class="fs-4 bi-people"></i> <span class="ms-1 d-none d-sm-inline">Customers</span> </a>
</li>

templates/board/board.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title_block %}

{% endblock %}

{% block content_block %}

{% endblock %}

templates/board/create_board.html
{% extends 'board/base.html' %}
{% load static %}

{% block title_block %}
Create a Board
{% endblock %}

{% block content_block %}
<h1>Create a Board</h1>
<form method="POST" , class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Create</button>
</form>
or <a href="{% url 'board:join_board' %}">join another board</a>
{% endblock %}

templates/board/show_board.html
{% extends 'board/base.html' %}
{% load static %}

{% block title_block %}
Show Board {{ board.name }}
{% endblock %}

{% block content_block %}
{% if board %}
{% include "partials/tasks.html" %}

{% else %}
<p>You don't have a board yet! <a href="{% url 'board:create_board' %}">Create a new board</a> or <a href="{% url 'board:join_board'">join an existing one</a>.</p>
{% endif %}
{% endblock %}