board/urls.py
from django.urls import path

from . import views

app_name = "board"
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("show_board/", views.ShowBoardView.as_view(), name="show_board"),
    path("add_task/", views.AddTaskView.as_view(), name="add_task"),
    path("create_board/", views.CreateBoardView.as_view(), name="create_board"),
    path(
        "user_profile/<int:pk>/", views.UserProfileView.as_view(), name="user_profile"
    ),
    # path('edit_task/<int:task_id>/', views.EditTaskView.as_view(), name='edit_task'),
    path("register/", views.RegisterView.as_view(), name="register"),
    path("about/", views.AboutView.as_view(), name="about"),
    path(
        "add_task_success/", views.AddTaskSuccessView.as_view(), name="add_task_success"
    ),
    path("add_task_fail/", views.AddTaskFailView.as_view(), name="add_task_fail"),
    path("user_list/", views.UserListView.as_view(), name="user_list"),
    # path('assign_task/<int:task_id>/', views.AssignTaskView.as_view(), name='assign_task'),
    path(
        "mark_completed/<int:task_id>/",
        views.MarkCompletedView.as_view(),
        name="mark_completed",
    ),
    path(
        "resign_task/<int:task_id>", views.ResignTaskView.as_view(), name="resign_task"
    ),
    path("join_board", views.JoinBoardView.as_view(), name="join_board"),
]

htmx_views = [
    path("tasks/<int:pk>/delete", views.delete_task, name="delete_task"),
    path("tasks/<int:pk>/edit", views.edit_task, name="edit_task"),
    path("tasks/<int:pk>/assign", views.assign_task, name="assign_task"),
    path("tasks/<int:pk>/resign", views.resign_task, name="resign_task"),
    path("tasks/<int:pk>/complete", views.complete_task, name="complete_task"),
]

urlpatterns += htmx_views

home_manager/urls.py
"""home_manager URL Configuration
"""
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

# from django_registration.backends.one_step.views import RegistrationView

urlpatterns = [
    path("", include("board.urls")),
    path("admin/", admin.site.urls),
    # path('accounts/', include('django_registration.backends.one_step.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path("messagebox/", include("messagebox.urls")),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

messagebox/urls.py
from django.urls import path

from . import views

app_name = "messagebox"
urlpatterns = [
    path("", views.MessagesView.as_view(), name="messages"),
    path("inbox/", views.InboxView.as_view(), name="inbox"),
    path("sent/", views.SentView.as_view(), name="sent"),
    path(
        "delete_message/<int:message_id>/",
        views.DeleteMessageView.as_view(),
        name="delete_message",
    ),
    path("new_message/", views.NewMessageView.as_view(), name="new_message"),
    path(
        "show_message/<int:message_id>",
        views.ShowMessageView.as_view(),
        name="show_message",
    ),
]

messagebox/models.py
from django.db import models
from django.contrib.auth.models import User


class Message(models.Model):
    from_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="sent_messages"
    )
    to_user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="received_messages"
    )
    title = models.CharField(max_length=128, default="Untitled")
    text = models.TextField()
    date = models.DateField(auto_now=True)
    read_status = models.BooleanField(default=False)

messagebox/forms.py
from django.contrib.auth.models import User
from .models import Message
from django.contrib.auth.models import User
from django.forms import ModelForm


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ["to_user", "title", "text"]

messagebox/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.core.exceptions import PermissionDenied
from django.shortcuts import render, redirect
from django.urls import reverse
from django.views import View

from .models import Message
from .forms import MessageForm


class MessagesView(LoginRequiredMixin, View):
    def get(self, request):
        """Show five latest of received and sent messages."""
        inbox = request.user.received_messages.order_by("-date")[:5]
        sent = request.user.sent_messages.order_by("-date")[:5]
        return render(
            request, "messagebox/messages.html", context={"inbox": inbox, "sent": sent}
        )


class InboxView(LoginRequiredMixin, View):
    def get(self, request):
        """Show received messages (newest first)."""
        inbox = request.user.received_messages.order_by("-date")
        return render(request, "messagebox/inbox.html", context={"inbox": inbox})


class SentView(LoginRequiredMixin, View):
    def get(self, request):
        """Show sent messages (newest first)."""
        sent = request.user.sent_messages.order_by("-date")
        return render(request, "messagebox/sent.html", context={"sent": sent})


class DeleteMessageView(LoginRequiredMixin, View):
    """Delete message with specified id and redirect to previous page."""

    pass


class NewMessageView(LoginRequiredMixin, View):
    """Create and send a message to another user."""

    def get(self, request):
        form = MessageForm()
        return render(request, "messagebox/new_message.html", context={"form": form})

    def post(self, request):
        form = MessageForm(request.POST)
        if form.is_valid():
            new_message = form.save(commit=False)
            new_message.from_user = request.user
            new_message.save()
            return redirect(reverse("messagebox:messages"))


class ShowMessageView(LoginRequiredMixin, View):
    def get(self, request, message_id):
        """Show message details."""
        message = Message.objects.get(pk=message_id)
        if message.to_user == request.user or message.from_user == request.user:
            return render(
                request, "messagebox/show_message.html", context={"message": message}
            )
        else:
            raise PermissionDenied

templates/messagebox/inbox.html
{% extends 'board/base.html' %}
{% load static %}

{% block title_block %}
Inbox
{% endblock %}

{% block content_block %}
<h3>Inbox:</h3>
{% if inbox %}
<ul>
    {% for message in inbox %}
    <li><a href="{% url 'messagebox:show_message' message.id %}">{{ message.title }}</a> from <a
            href="">{{ message.from_user }}</a></li>
    {% endfor %}
</ul>
{% else %}
<p>You have no messages</p>
{% endif %}

{% endblock %}

templates/messagebox/messages.html
{% extends 'board/base.html' %}
{% load static %}

{% block title_block %}
Messages
{% endblock %}

{% block content_block %}
<h3><a href="{% url 'messagebox:new_message' %}">New Message</a></h3>
<h3>Inbox:</h3>
<a href="{% url 'messagebox:inbox' %}">See all</a>
{% if inbox %}
<ul>
    {% for message in inbox %}
    <li>{{ message.title }} from {{ message.from_user }}</li>
    {% endfor %}
</ul>
{% else %}
<p>You have no messages</p>
{% endif %}

<h3>Sent:</h3>
<a href="{% url 'messagebox:sent' %}">See all</a>
{% if sent %}
<ul>
    {% for message in sent %}
    <li>{{ message.title }} to {{ message.to_user }}</li>
    {% endfor %}
</ul>
{% else %}
<p>Empty</p>
{% endif %}
{% endblock %}

templates/messagebox/new_message.html
{% extends 'board/base.html' %}
{% load static %}

{% block title_block %}
Send a Message
{% endblock %}

{% block content_block %}
<h1>Send a message</h1>
<form method="POST" , class="form-group">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Send</button>
</form>
{% endblock %}

templates/messagebox/sent.html
{% extends 'board/base.html' %}
{% load static %}

{% block title_block %}
Sent messages
{% endblock %}

{% block content_block %}

<h3>Sent:</h3>
{% if sent %}
<ul>
    {% for message in sent %}
    <li>{{ message.title }} to {{ message.to_user }}</li>
    {% endfor %}
</ul>
{% else %}
<p>Empty</p>
{% endif %}
{% endblock %}

templates/messagebox/show_message.html
{% extends 'board/base.html' %}
{% load static %}

{% block title_block %}
{{ message.title }}
{% endblock %}

{% block content_block %}
<h3>{{ message.title }}</h3>
<p>From: {{ message.from_user }}</p>
<p>{{ message.text }}</p>
<a href="{% url 'messagebox:inbox' %}">Back to inbox</a>
{% endblock %}